version: '3'

services:
  viewer:
    image: registry.gitlab.com/ailab/tezaurs:${TAG}
    restart: unless-stopped
    environment:
      - PORT=9050
      - DB_URL
      - DICT=tezaurs
      - DB_SCHEMA=dict
      - RELEASE=1
      - APP_MODE=public
      - DEBUG
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    network_mode: host
